migrate(
  (app) => {
    const col = app.findCollectionByNameOrId('contracts')
    if (!col.fields.getByName('regime_bens')) col.fields.add(new TextField({ name: 'regime_bens' }))
    if (!col.fields.getByName('nome_conjuge'))
      col.fields.add(new TextField({ name: 'nome_conjuge' }))
    if (!col.fields.getByName('imovel_financiado'))
      col.fields.add(new BoolField({ name: 'imovel_financiado' }))
    if (!col.fields.getByName('imovel_locado'))
      col.fields.add(new BoolField({ name: 'imovel_locado' }))
    if (!col.fields.getByName('imovel_inventario'))
      col.fields.add(new BoolField({ name: 'imovel_inventario' }))
    if (!col.fields.getByName('possui_onus')) col.fields.add(new BoolField({ name: 'possui_onus' }))
    if (!col.fields.getByName('valor_fgts')) col.fields.add(new NumberField({ name: 'valor_fgts' }))
    if (!col.fields.getByName('parcelas')) col.fields.add(new NumberField({ name: 'parcelas' }))
    if (!col.fields.getByName('prazo_pagamento'))
      col.fields.add(new TextField({ name: 'prazo_pagamento' }))
    if (!col.fields.getByName('prazo_desocupacao'))
      col.fields.add(new TextField({ name: 'prazo_desocupacao' }))
    if (!col.fields.getByName('ocupacao_imovel'))
      col.fields.add(new TextField({ name: 'ocupacao_imovel' }))
    if (!col.fields.getByName('pep')) col.fields.add(new BoolField({ name: 'pep' }))
    if (!col.fields.getByName('procurador')) col.fields.add(new BoolField({ name: 'procurador' }))
    if (!col.fields.getByName('matricula_atualizada'))
      col.fields.add(new BoolField({ name: 'matricula_atualizada' }))
    if (!col.fields.getByName('debitos_condominio'))
      col.fields.add(new BoolField({ name: 'debitos_condominio' }))
    app.save(col)
  },
  (app) => {
    const col = app.findCollectionByNameOrId('contracts')
    col.fields.removeByName('regime_bens')
    col.fields.removeByName('nome_conjuge')
    col.fields.removeByName('imovel_financiado')
    col.fields.removeByName('imovel_locado')
    col.fields.removeByName('imovel_inventario')
    col.fields.removeByName('possui_onus')
    col.fields.removeByName('valor_fgts')
    col.fields.removeByName('parcelas')
    col.fields.removeByName('prazo_pagamento')
    col.fields.removeByName('prazo_desocupacao')
    col.fields.removeByName('ocupacao_imovel')
    col.fields.removeByName('pep')
    col.fields.removeByName('procurador')
    col.fields.removeByName('matricula_atualizada')
    col.fields.removeByName('debitos_condominio')
    app.save(col)
  },
)
